---
- hosts: all
  become: true
  tasks:
    - name: Install gnome-tweak-tool
      dnf:
        name: gnome-tweak-tool
        state: present
        
    - name: Install tlp, htop, btop
      dnf:
        name:
          - tlp
          - tlp-rdw
          - htop
          - btop
        state: present
    - name: Remove tuned to prevent conflicts with tlp
      dnf:
        name:
          - tuned
          - tuned-ppd
        state: absent

    - name: Enable services for tlp
      command: systemctl enable tlp.service
    - name: Mask services conflicting with tlp
      command: systemctl mask systemd-rfkill.service systemd-rfkill.socket

    - name: Install wl-clipboard
      dnf:
        name: wl-clipboard
        state: present
    
    - name: Install tree
      dnf:
        name: tree
        state: present

    - name: Install fastfetch
      dnf:
        name: fastfetch
        state: present

    - name: Enable varlad/onefetch copr repository
      command: dnf copr enable -y varlad/onefetch
      register: copr_result
      changed_when: "'Repository successfully enabled.' in copr_result.stdout"

    - name: Install onefetch
      dnf:
        name: onefetch
        state: present

    - name: Install wget
      dnf:
        name: wget
        state: present

    - name: Eable Fontmanager COPR repository
      shell: dnf copr enable jerrycasiano/FontManager -y
      register: copr_result
      changed_when: "'Repository successfully enabled.' in copr_result.stdout"
    
    - name: Install font-manager
      dnf:
        name: font-manager
        state: present   

    - name: Install bottles
      dnf:
        name: bottles
        state: present

    - name: Install btrfs-assistant
      dnf:
        name: btrfs-assistant
        state: present

    - name: Install gparted
      dnf:
        name: gparted
        state: present
    - name: Install wavemon
      dnf:
        name: wavemon
        state: present

    - name: Install handbrake
      dnf:
        name: handbrake
        state: present
    - name: Install handbrake-gui
      dnf:
        name: handbrake-gui
        state: present

    - name: Install Distrobox
      dnf:
        name: distrobox
        state: present

    - name: Add Signal repository
      command: dnf config-manager addrepo --from-repofile=https://download.opensuse.org/repositories/network:im:signal/Fedora_42/network:im:signal.repo
      register: repo_result
      changed_when: "'Repository successfully added.' in repo_result.stdout"

    - name: Install Signal
      dnf:
        name: signal-desktop
        state: present
