---
- hosts: all
  become: true

  tasks:
    - name: Create cursor directory
      file:
        path: /opt/cursor
        state: directory
        mode: '0755'
    
    - name: Download Cursor AppImage
      shell: |
        curl -L -o /opt/cursor/cursor.appimage https://downloads.cursor.com/production/d01860bc5f5a36b62f8a77cd42578126270db343/linux/x64/Cursor-1.4.2-x86_64.AppImage
      args:
        creates: /opt/cursor/cursor.appimage
    
    - name: Make Cursor AppImage executable
      file:
        path: /opt/cursor/cursor.appimage
        mode: '0755'
        owner: root
        group: root
    
    - name: Create Cursor desktop entry
      copy:
        dest: /usr/share/applications/cursor.desktop
        content: |
          [Desktop Entry]
          Name=Cursor
          Comment=AI-powered code editor
          Exec=/opt/cursor/cursor.appimage
          Icon=/opt/cursor/cursor.appimage
          Terminal=false
          Type=Application
          Categories=Development;TextEditor;IDE;
          StartupNotify=true
          StartupWMClass=cursor
        mode: '0644'
    
    - name: Update desktop database
      command: update-desktop-database /usr/share/applications/
      changed_when: false
