---
- hosts: all
  become: true
  become_user: "{{ target_user }}"
  vars:
    target_user: shawon
    flatpaks:
      - com.discordapp.Discord
      - com.spotify.Client
      - org.signal.Signal
      - org.telegram.desktop
      - com.github.tchx84.Flatseal
      - com.obsproject.Studio
      - md.obsidian.Obsidian
      - com.mattjakeman.ExtensionManager
      - org.gnome.World.PikaBackup
      - org.filezillaproject.Filezilla
      - io.podman_desktop.PodmanDesktop
      - com.github.jeromerobert.pdfarranger
      - de.haeckerfelix.Shortwave
      - com.anydesk.Anydesk
      - org.localsend.localsend_app
      - org.torproject.torbrowser-launcher
      - org.zotero.Zotero
      - org.mozilla.Thunderbird

  tasks:
    - name: Add Flathub remote for user
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install Flatpak applications for user
      flatpak:
        name: "{{ item }}"
        state: present
        remote: flathub
        method: user
      loop: "{{ flatpaks }}"
