---
- hosts: localhost
  become: true
  tasks:
    - name: Install tlp, htop, btop
      dnf:
        name:
          - tlp
          - tlp-rdw
          - htop
          - btop
        state: present

    - name: Remove tuned to prevent conflicts with tlp
      dnf:
        name:
          - tuned
          - tuned-ppd
        state: absent

    - name: Install xclip
      dnf:
        name: xclip
        state: present
    
    - name: Install tree
      dnf:
        name: tree
        state: present
        