---
- hosts: all
  become: true
  tasks:
    - name: Install Steam
      dnf:
        name: steam
        state: present

    - name: Install Steam-Devices
      dnf:
        name: steam-devices
        state: present

    - name: Install Lutris
      dnf:
        name: lutris
        state: present

    - name: Install goverlay
      dnf:
        name: goverlay
        state: present

    - name: Install mangohud
      dnf:
        name: mangohud
        state: present

    - name: Install gamemode
      dnf:
        name: gamemode
        state: present

- hosts: all
  become: false
  tasks:
    - name: Install Protonup-Qt
      command: flatpak install flathub net.davidotek.pupgui2 -y


