---
- hosts: localhost
  become: true
  tasks:
    - name: Install tlp, htop, btop
      dnf:
        name:
          - tlp
          - tlp-rdw
          - htop
          - btop
        state: present

    - name: Remove tuned to prevent conflicts with tlp
      dnf:
        name:
          - tuned
          - tuned-ppd
        state: absent

    - name: Install xclip
      dnf:
        name: xclip
        state: present
    
    - name: Install tree
      dnf:
        name: tree
        state: present

    - name: Install fastfetch
      dnf:
        name: fastfetch
        state: present

    - name: Enable varlad/onefetch copr repository
      ansible.builtin.command: dnf copr enable -y varlad/onefetch
      register: copr_result
      changed_when: "'Repository successfully enabled.' in copr_result.stdout"

    - name: Install onefetch
      ansible.builtin.dnf:
        name: onefetch
        state: present
    
        