---
- hosts: all
  become: true
  tasks:
    - name: Install gnome-tweak-tool
      dnf:
        name: gnome-tweak-tool
        state: present
        
    - name: Install tlp, htop, btop
      dnf:
        name:
          - tlp
          - tlp-rdw
          - htop
          - btop
        state: present

    - name: Remove tuned to prevent conflicts with tlp
      dnf:
        name:
          - tuned
          - tuned-ppd
        state: absent

    - name: Install xclip
      dnf:
        name: xclip
        state: present
    
    - name: Install tree
      dnf:
        name: tree
        state: present

    - name: Install fastfetch
      dnf:
        name: fastfetch
        state: present

    - name: Enable varlad/onefetch copr repository
      command: dnf copr enable -y varlad/onefetch
      register: copr_result
      changed_when: "'Repository successfully enabled.' in copr_result.stdout"

    - name: Install onefetch
      dnf:
        name: onefetch
        state: present

    - name: Install wget
      dnf:
        name: wget
        state: present

    - name: Install OpenBangla Keyboard
      shell: bash -c "$(wget -q https://raw.githubusercontent.com/OpenBangla/OpenBangla-Keyboard/master/tools/install.sh -O -)"
      args:
        warn: false

    - name: Install KDE Connect
      dnf:
        name: kdeconnect
        state: present

    
        