---
- hosts: all
  become: true

  tasks:
    - name: Install akmod-nvidia
      dnf:
        name: akmod-nvidia
        state: present
    - name: Setup CUDA Toolkit
      shell: |
       dnf config-manager addrepo --from-repofile=https://developer.download.nvidia.com/compute/cuda/repos/fedora41/$(uname -m)/cuda-fedora41.repo
       dnf clean all
       dnf module disable nvidia-driver
       dnf config-manager setopt cuda-fedora41-$(uname -m).exclude=nvidia-driver,nvidia-modprobe,nvidia-persistenced,nvidia-settings,nvidia-libXNVCtrl,nvidia-xconfig
       dnf -y install cuda-toolkit
    - name: Run OS-Prober
      command: os-prober
    - name: Update grub entries
      command: grub2-mkconfig -o /etc/grub2-efi.cfg
