---
- hosts: all
  become: true
  pre_tasks:
    - name: Install python3-dnf
      raw: dnf install -y python3-dnf
      register: result
      changed_when: "'Nothing to do.' not in result.stdout"
    - name: Tweak dnf
      blockinfile:
        path: /etc/dnf/dnf.conf
        block: |
          fastestmirror=True
          max_parallel_downloads=20 
          defaultyes=True
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
    - name: Update system
      command: dnf update -y
    - name: Install dnf-utils
      command: dnf install -y dnf-utils
    - name: Install dnf-plugins-core
      command: dnf install -y dnf-plugins-core
  tasks:
    - name: Add rpm-fusion-free
      shell: dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
    - name: Add rpm-fusion-nonfree
      shell: dnf install -y https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
    - name: Enable H.264
      command: dnf config-manager setopt fedora-cisco-openh264.enabled=1
